name: Local Test Development

on:
  pull_request:
    types: [opened]

jobs:
  run-on-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run GPT-i18n
        uses: ./
        with:
          input1: ${{ github.event.pull_request.head.sha }}
          input2: "Hello world"
