name: Publish gpt-i18n

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    name: Build and Publish gpt-i18n
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: balverine/gpt-i18n:latest
          platforms: linux/amd64

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
# name: Local Test Development
#
# on:
#   pull_request:
#     types: [opened]
#   push:
#     branches: "**"
#
# jobs:
#   run-on-pr:
#     runs-on: ubuntu-latest
#
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2
#
#       - name: My step
#         uses: docker://balverine/gpt-i18n:1
#         with: # if your Docker image expects inputs
#           input1: "value"
#
# - name: Run GPT-i18n (local)
#   uses: ./
#   with:
#     input1: ${{ github.event.pull_request.head.sha }}
#     input2: "Hello world"
#
# - name: Run GPT-i18n (remote)
#   uses: OlegGulevskyy/GPT-i18n@1.0.0
#   with:
#     input1: ${{ github.event.pull_request.head.sha }}
#     input2: "Hello world"
